# Exam study guides

## Exam 1 {-}

### Neuroanatomy {-}

- Meninges
- Lobes of the cerebral cortex
- Components of the
    - Forebrain
        - hypothalamus != hippocampus
    - Midbrain
    - Hindbrain
    - What ventricles are landmarks
- Planes of section
    - Axial/horizontal
    - Sagittal
    - Coronal/frontal
- CNS vs. PNS
- Components of the ANS
    - Sympathetic
    - Parasympathetic

### Methods {-}

- Functional vs. structural
- Spatial vs. temporal resolution

### Cells {-}

- Neuron anatomy
- Resting potential
    - What ions, concentrated where
    - Force of diffusion
    - Electrostatic force
- Action potential
    - Voltage-gated channels
    - What's happening in
        - Rising phase
        - Falling phase
- Glia
    - Astrocytes
    - Myelinating cells
        - Cell types
        - Function of

## Exam 2 {-}

### Methods {-}

- Structural vs. functional

### Neuroanatomy {-}

- Hypothalamus
  - Anterior/posterior pituitary
- Sympathetic/Parasympathetic nervous system
- Adrenal gland
  - Medulla
  - Cortex
- Cerebral cortex
- Cerebellum
- Midbrain
  - Tectum
  - Tegmentum
    - Ventral Tegmental Area
    - Substantia Nigra

- Glial cell types

### Resting & action potentials {-}

- What ions are concentrated where (inside/outside)
  - Na+
  - K+
  - A-
  - Cl-
- Steps/phases of action potential (what's happening to ions & channels)
  - Onset at threshold
  - Rising phase
  - Peak
  - Falling phase
  - Reset

### Neurotransmitters {-}

- Steps in neurotransmitter release

- Amino acids
  - Glutamate
  - GABA
- Acetylcholine
- Monoamines
  - Dopamine (DA)
  - Norepinephrine (NE)/Noradrenaline (NA)
  - Serotonin/5-HT
  - Histamine
  - Melatonin

- Anatomy (where released)
- Disorders/conditions linked to specific neurotransmitter systems

- Ionotropic vs. metabotropic receptors
- Excitatory Post-Synaptic Potentials (EPSPs)/Inhibitory Post-Synaptic Potentials

### Hormones {-}

- Hormones, where released and function of
  - Cortisol
  - Oxytocin
  - Melatonin
  - AVP/ADH
  
- HPA axis, SAM axis
  - Anatomy
  - Hormones and neurotransmitters released

### Evolution {-}
  
- Principles of evolution; evidence for
- Milestones of history of life on Earth
- Humans vs. other animals brain size, structure, composition
  
## Exam 3 {-}

### Methods {-}

- Diffusion Tensor Imaging (DTI)

### Neuroanatomy {-}

- Location and names of cerebral ventricles
- What sensory/motor areas are located in each lobe

### Neurochemistry {-}

- Events leading to release of neurotransmitter

### Evolution & Development {-}

- What measure(s) of brain structure or function _decline_ in childhood and adolescence?
- Where do cells that can make new neurons & glia in adult mammals reside?
- How mammalian brains compare
- Human cerebellum size vs. non-human animals

### Psychopathology {-}

- Monoamine hypothesis of depression
- Evidence for link between serotonin dysfunction and depression
- SSRIs and SNRIs
- What is ECT and how is it used
- Treatments for bipolar disorder
- Risk factors for depression, schizophrenia
- Brain abnormalities in schizophrenia
- Dopamine hypothesis of schizophrenia and its flaws and alternatives

### Emotion {-}

- Locationist vs. constructionist account
- Focal points of Plutchik's perspective
- Non-human animal behaviors/physiology vs. human
- Neurotransmitters involved in affective states, responses
- Effect of stimulation of "reward" pathway, main sites
- Brain sites that release dopamine
- Typical cortisol release patterns
- Acute vs. chronic stressors

### Sensory systems {-}

- Interoception vs. exteroception
- Properties of cutaneous (skin) receptors
- Why spicy-tasting foods also seem hot
- What sensory signals propagate quickly and which slowly
- Receptive field sizes and relationship with sensitivity
- Anatomy of somatosensory system

## [Exam 4](the-cerebral-symphony.html#exam-4-review) {-}

